// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbdgilhtmjlzqgpkeatz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZGdpbGh0bWpsenFncGtlYXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjA4MjgsImV4cCI6MjA3NDUzNjgyOH0.uhC55ihnxFjWRx4E19V1GyRL4-gfl6L3tobi06zXkKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});